### PR TITLE
Updated checksum to match binary artifact

### PR DESCRIPTION
**Pull request by andibeqiri**

### CODE REVIEW

**Comment by JeremieDaigle2** [comment]
Anytime you guys are ready ! :D this is blocking

**Comment by galunecandrey** [comment]
Please consider this PR as soon as possible. We also have this problem on CI/CD. One of the packages we use has a dependency on AppsFlyerLib. Clearing caches doesn't help.

**Comment by JohnnyTseng** [comment]
@af-obodovskyi Would you please merge this PR? Thank you!

**Comment by srdanrasic** [comment]
@amit-kremer93 @af-obodovskyi could you look into this with urgency? This is breaking many organisation's CIs.

**Comment by hbanzon** [comment]
Thank you for prepping this PR!  I could benefit from it as well 🙏

**Comment by richroguetech** [comment]
Please merge this. I need this!

**Review by pjtnt11 — APPROVED** [review]

**Review by serdaraslanfetch — APPROVED** [review]

**Comment by af-obodovskyi** [comment]
@richroguetech , @hbanzon , @srdanrasic , @JohnnyTseng 

@scottlemke Please consider using one of the following repositories for the SPM. SPM support will be removed from the main repository because of the extremely long checkout time, which affects the release process.

For statically linked library
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static

For dynamically linked library
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic

For Strict (No IDFA colection) library
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Strict

**Comment by mustafauskuplu** [comment]
@af-obodovskyi I tried the static linked library you mentioned (**6.14.0**) but there is still a mismatch between the checksum that is provided in the manifest and the actual checksum of the binary.

> checksum of downloaded artifact of binary target 'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)

**Comment by ftp27** [comment]
@af-obodovskyi what release processes are you talking about? It's just links to binaries and zero source code :D With the same result you can publish separate version tags in separate branches

**Comment by af-obodovskyi** [comment]
@ftp27 not the release process, SPM package integration time. I will edit my comment

**Comment by hbanzon** [comment]
@af-obodovskyi I get the following error using the Static library.  Seems liek there's some changes that will be required on our end if we switch repos.  

`AppsFlyerLib` is not a valid configured external dependency

**Comment by hbanzon** [comment]
Can we get more of a ramp up time to adapt to the new repos but in the meantime merge any of the PRs that fix this issue?

**Comment by scottlemke** [comment]
> @af-obodovskyi I get the following error using the Static library. Seems liek there's some changes that will be required on our end if we switch repos.
> 
> `AppsFlyerLib` is not a valid configured external dependency

@hbanzon I assume you're using Tuist too? If so, you  need to reference the static of dynamic library name to fix that issue. Something like:
` .external(name: "AppsFlyerLib-Static")` or ` .external(name: "AppsFlyerLib-Dynamic")`

**Comment by hbanzon** [comment]
Thank you @scottlemke!

**Pull request closed without merging**
