### PR TITLE
fix_v6.14.0_checksum Fix the checksum for https://github.com/AppsFlye…

### PR DESCRIPTION
**Pull request by iharkatkavets**
Fix a checksum in Package.swift for https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/download/6.14.0

### CODE REVIEW

**Comment by iharkatkavets** [comment]
This pull request fixes the issue https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/280

**Review by sudhanshu-probo — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by alessiolapenna** [comment]
Please release this, since it's blocking the update of the sdk with privacy manifest and Apple's deadline is May 1st. 
We need this asap.

**Comment by iharkatkavets** [comment]
For everyone, who suffer because of the checksum issue, there is another repository for dynamic version of `AppsFlyer` lib, 
```swift
 # For dynamically linked library
 https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic
```

You can integrate it into your project only via **Swift Package Manager**.

**Comment by matejpcal** [comment]
@iharkatkavets  Do we know when this will be merged?

**Comment by iharkatkavets** [comment]
> @iharkatkavets Do we know when this will be merged?

I'm not a `AppsFlyer` developer, so don't have the rights to merge the pull request to the repository. Have no idea why the pull request got stuck and can't be merged. Is there a way to ping the contributors?

**Comment by iharkatkavets** [comment]
@af-fess Could you please merge the pull request and prepare a new release of the library?

**Review by DylanBarteling — APPROVED** [review]

**Pull request closed without merging**
